(function(){
'use strict';
const CFG=window.BHATTI_CONFIG||{};const db=window.supabase.createClient(CFG.supabaseUrl,CFG.supabasePublishableKey);const API=(CFG.apiBase||'').replace(/\/$/,'');
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const money=n=>'PKR '+Number(n||0).toLocaleString();
let addresses=[];
async function token(){const r=await db.auth.getSession();return r.data.session?.access_token||''}
async function api(path,opt={}){const t=await token();const r=await fetch(API+path,{...opt,headers:{'Content-Type':'application/json',...(opt.headers||{}),...(t?{Authorization:'Bearer '+t}:{})}});const b=await r.json().catch(()=>({}));if(!r.ok)throw Error(b.error||'Request failed');return b}
function show(){const el=$('#accountSystem');if(!el)return;el.classList.add('open');el.setAttribute('aria-hidden','false');document.body.classList.add('account-open')}
function hide(){const el=$('#accountSystem');if(!el)return;el.classList.remove('open');el.setAttribute('aria-hidden','true');document.body.classList.remove('account-open')}
function view(name){$$('[data-account-view]').forEach(b=>b.classList.toggle('active',b.dataset.accountView===name));$$('[data-account-panel]').forEach(p=>p.classList.toggle('active',p.dataset.accountPanel===name));if(name==='addresses')loadAddresses();if(name==='orders')loadOrders()}
function clearAddress(){const f=$('#v2AddressForm');if(!f)return;f.reset();$('#v2AddressId').value='';$('#v2AddressMode').textContent='NEW ADDRESS';$('#v2AddressMessage').textContent=''}
function editAddress(a){$('#v2AddressId').value=a.id;$('#v2AddressLabel').value=a.label||'';$('#v2Recipient').value=a.recipient_name||'';$('#v2AddressPhone').value=a.phone||'';$('#v2City').value=a.city||'';$('#v2AddressText').value=a.address_line||'';$('#v2Default').checked=!!a.is_default;$('#v2AddressMode').textContent='EDIT ADDRESS';$('#v2AddressForm').scrollIntoView({behavior:'smooth',block:'center'})}
async function loadProfile(){const s=(await db.auth.getSession()).data.session;if(!s){window.openAccount?.();return false}try{const r=await api('/account/profile');const p=r.data||{};const name=p.full_name||s.user.user_metadata?.full_name||s.user.email?.split('@')[0]||'Customer';$('#accountIdentity').textContent=s.user.email||'';$('#accountHeroTitle').textContent='Welcome, '+name.split(' ')[0]+'.';$('#v2FullName').value=p.full_name||name;$('#v2Phone').value=p.phone||'';$('#v2Email').value=s.user.email||'';$('#statProfile').textContent=name.split(' ')[0];$('#accountSignOut').hidden=false;return true}catch(e){$('#accountHeroText').textContent=e.message;return false}}
async function loadAddresses(){try{addresses=(await api('/account/addresses')).data||[];$('#statAddresses').textContent=addresses.length;$('#v2AddressList').innerHTML=addresses.length?addresses.map(a=>'<article class="account-card-item '+(a.is_default?'default':'')+'"><header><strong>'+esc(a.label||'Address')+'</strong><small>'+(a.is_default?'DEFAULT':'SAVED')+'</small></header><p>'+esc(a.recipient_name||'')+(a.phone?' · '+esc(a.phone):'')+'<br>'+esc(a.address_line)+', '+esc(a.city)+'</p><div class="item-actions"><button type="button" data-edit-address="'+esc(a.id)+'">Edit</button><button type="button" data-delete-address="'+esc(a.id)+'">Remove</button></div></article>').join(''):'<div class="empty-account"><strong>No saved addresses.</strong>Add one to make checkout faster.</div>';$$('[data-edit-address]').forEach(b=>b.onclick=()=>editAddress(addresses.find(a=>a.id===b.dataset.editAddress)));$$('[data-delete-address]').forEach(b=>b.onclick=()=>deleteAddress(b.dataset.deleteAddress))}catch(e){$('#v2AddressList').innerHTML='<div class="empty-account"><strong>Could not load addresses.</strong>'+esc(e.message)+'</div>'}}
async function deleteAddress(id){if(!confirm('Remove this saved address?'))return;try{await api('/account/addresses/'+id,{method:'DELETE'});clearAddress();loadAddresses()}catch(e){alert(e.message)}}
async function saveAddress(e){e.preventDefault();const id=$('#v2AddressId').value;const body={label:$('#v2AddressLabel').value.trim(),recipient_name:$('#v2Recipient').value.trim(),phone:$('#v2AddressPhone').value.trim(),city:$('#v2City').value.trim(),address_line:$('#v2AddressText').value.trim(),is_default:$('#v2Default').checked};try{await api(id?'/account/addresses/'+id:'/account/addresses',{method:id?'PUT':'POST',body:JSON.stringify(body)});$('#v2AddressMessage').textContent='Saved.';clearAddress();loadAddresses()}catch(e){$('#v2AddressMessage').textContent=e.message}}
async function loadOrders(){try{const r=await api('/orders/me');const rows=r.data||[];$('#statOrders').textContent=rows.length;$('#v2OrderList').innerHTML=rows.length?rows.map(o=>'<article class="order-item"><header><strong>'+esc(o.order_number)+'</strong><span class="status">'+esc(o.status)+'</span></header><div class="order-meta"><span>'+new Date(o.created_at).toLocaleDateString()+'</span><span>'+money(o.total)+'</span><span>'+esc(o.payment_status||'Unpaid')+'</span></div><p>'+((o.order_items||[]).map(i=>esc(i.product_name)+' × '+i.quantity).join('<br>')||'Order details unavailable')+'</p><div class="order-actions">'+(['Pending','Confirmed'].includes(o.status)?'<button data-order-action="cancel" data-order-id="'+esc(o.id)+'">Request cancellation</button>':'')+(o.status==='Delivered'?'<button data-order-action="return" data-order-id="'+esc(o.id)+'">Request return</button>':'')+'</div></article>').join(''):'<div class="empty-account"><strong>No orders yet.</strong>Your Bhatti order history will appear here.</div>';$$('[data-order-action]').forEach(b=>b.onclick=()=>orderAction(b.dataset.orderId,b.dataset.orderAction))}catch(e){$('#v2OrderList').innerHTML='<div class="empty-account"><strong>Orders unavailable.</strong>'+esc(e.message)+'</div>'}}
async function orderAction(id,action){const reason=prompt(action==='cancel'?'Reason for cancellation (optional):':'Reason for return (optional):')||'';try{await api('/orders/'+id+'/action',{method:'POST',body:JSON.stringify({action,reason})});loadOrders()}catch(e){alert(e.message)}}
async function openAccountV2(){const s=(await db.auth.getSession()).data.session;if(!s){document.querySelector('#authModal')?.classList.add('open');return}show();await loadProfile();view('overview');loadAddresses();loadOrders()}
async function saveProfile(e){e.preventDefault();const msg=$('#v2ProfileMessage');try{await api('/account/profile',{method:'PATCH',body:JSON.stringify({full_name:$('#v2FullName').value.trim(),phone:$('#v2Phone').value.trim()})});msg.textContent='Profile saved.';await loadProfile()}catch(x){msg.textContent=x.message}}
$$('[data-account-close]').forEach(b=>b.onclick=hide);
$$('[data-account-view]').forEach(b=>b.onclick=()=>view(b.dataset.accountView));
$$('[data-go-view]').forEach(b=>b.onclick=()=>view(b.dataset.goView));
$('#v2ProfileForm')?.addEventListener('submit',saveProfile);$('#v2AddressForm')?.addEventListener('submit',saveAddress);$('#v2NewAddress')?.addEventListener('click',()=>{clearAddress();$('#v2AddressLabel').focus()});$('#v2CancelAddress')?.addEventListener('click',clearAddress);$('#accountSignOut')?.addEventListener('click',async()=>{await db.auth.signOut();hide();location.reload()});
$('#accountButton')?.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();openAccountV2()});
window.openAccount=openAccountV2;
db.auth.onAuthStateChange((event,s)=>{if(s&&event==='SIGNED_IN'){}});
})();