const C=window.BHATTI_CONFIG,sb=window.supabase.createClient(C.supabaseUrl,C.supabasePublishableKey),API=C.apiBase.replace(/\/$/,'');let session=null,orders=[],products=[],customers=[],reviews=[];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];const money=n=>'PKR '+Number(n||0).toLocaleString();const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
async function api(path,opt={}){const {data}=await sb.auth.getSession(),t=data.session?.access_token||'';const r=await fetch(API+path,{...opt,headers:{'Content-Type':'application/json',...(t?{Authorization:'Bearer '+t}:{})}});const b=await r.json().catch(()=>({}));if(!r.ok)throw Error(b.error||'Request failed');return b}
async function start(){const {data}=await sb.auth.getSession();session=data.session;if(!session)return;try{const p=await api('/account/profile');if(p.data.role!=='admin')throw Error('This account is not an administrator.');$('#loginView').hidden=true;$('#appView').hidden=false;loadAll()}catch(e){$('#loginMessage').textContent=e.message;await sb.auth.signOut()}}
$('#loginForm').onsubmit=async e=>{e.preventDefault();try{const {error}=await sb.auth.signInWithPassword({email:$('#adminEmail').value,password:$('#adminPassword').value});if(error)throw error;start()}catch(e){$('#loginMessage').textContent=e.message}};
$('#logout').onclick=async()=>{await sb.auth.signOut();location.reload()};
$$('aside button').forEach(b=>b.onclick=()=>{ $$('aside button').forEach(x=>x.classList.remove('active'));$$('.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('[data-view="'+b.dataset.section+'"]').classList.add('active')});
async function loadAll(){await Promise.all([loadSummary(),loadOrders(),loadProducts(),loadCustomers(),loadReviews()])}
async function loadSummary(){const r=await api('/admin/summary');$('#stats').innerHTML=Object.entries(r.data).map(([k,v])=>'<div class="stat"><b>'+v+'</b><span>'+k.replaceAll('_',' ')+'</span></div>').join('')}
async function loadOrders(){const r=await api('/admin/orders');orders=r.data||[];renderOrders()}
function renderOrders(){const q=($('#orderSearch')?.value||'').toLowerCase(),s=$('#orderStatus')?.value||'All';const list=orders.filter(o=>(s==='All'||o.status===s)&&(!q||(o.order_number+' '+o.customer_name+' '+o.customer_phone).toLowerCase().includes(q)));$('#orders').innerHTML=list.map(o=>'<div class="card"><div class="card-head"><div><strong>'+esc(o.order_number)+'</strong><div>'+esc(o.customer_name)+' · '+esc(o.customer_phone)+'</div><small>'+new Date(o.created_at).toLocaleString()+'</small></div><span class="tag">'+esc(o.status)+'</span></div><div class="order-items">'+o.order_items.map(i=>esc(i.product_name)+' × '+i.quantity+' — '+money(i.line_total)).join('<br>')+'</div><strong>Total '+money(o.total)+'</strong><div>'+esc(o.city)+' · '+esc(o.address_line)+'</div><div class="actions"><select data-order-status="'+o.id+'">'+['Pending','Confirmed','Processing','Packed','Shipped','Out for Delivery','Delivered','Return Requested','Returned','Cancelled'].map(x=>'<option '+(x===o.status?'selected':'')+'>'+x+'</option>').join('')+'</select><select data-order-pay="'+o.id+'">'+['Unpaid','Payment Pending','Partially Paid','Paid','Refund Pending','Failed','Refunded'].map(x=>'<option '+(x===o.payment_status?'selected':'')+'>'+x+'</option>').join('')+'</select><button class="btn" data-save-order="'+o.id+'">Save workflow</button></div></div>').join('')||'<div class="card">No orders match.</div>';$$('[data-save-order]').forEach(b=>b.onclick=()=>saveOrder(b.dataset.saveOrder))}
async function saveOrder(id){try{await api('/admin/orders/'+id,{method:'PATCH',body:JSON.stringify({status:$('[data-order-status="'+id+'"]')?.value,payment_status:$('[data-order-pay="'+id+'"]')?.value})});await loadOrders();await loadSummary()}catch(e){alert(e.message)}}
async function loadProducts(){const r=await api('/admin/products');products=r.data||[];$('#products').innerHTML=products.map(p=>'<div class="card"><div class="card-head"><div><strong>'+esc(p.name)+'</strong><div>'+esc(p.category)+' · '+esc(p.sku||'No SKU')+'</div></div><span class="tag">'+(p.active?'PUBLISHED':'HIDDEN')+'</span></div><div>'+money(p.price)+' · Stock '+(p.inventory?.[0]?.quantity??0)+' · Reorder '+(p.inventory?.[0]?.reorder_level??0)+'</div><div class="actions"><button class="btn" data-edit-product="'+p.id+'">Edit</button><button class="btn" data-toggle-product="'+p.id+'">'+(p.active?'Hide':'Publish')+'</button></div></div>').join('')||'<div class="card">No products.</div>';$$('[data-edit-product]').forEach(b=>b.onclick=()=>editProduct(products.find(p=>p.id===b.dataset.editProduct)));$$('[data-toggle-product]').forEach(b=>b.onclick=()=>toggleProduct(products.find(p=>p.id===b.dataset.toggleProduct)))}
function editProduct(p){$('#productId').value=p.id;$('#productName').value=p.name;$('#productCategory').value=p.category;$('#productPrice').value=p.price;$('#productSku').value=p.sku||'';$('#productQty').value=p.inventory?.[0]?.quantity??0;$('#productReorder').value=p.inventory?.[0]?.reorder_level??5;$('#productDescription').value=p.description||'';$('#productImage').value=p.image_url||'';$('#productActive').checked=p.active;scrollTo({top:0,behavior:'smooth'})}
$('#productForm').onsubmit=async e=>{e.preventDefault();const id=$('#productId').value,b={name:$('#productName').value,category:$('#productCategory').value,price:Number($('#productPrice').value),sku:$('#productSku').value,quantity:Number($('#productQty').value),reorder_level:Number($('#productReorder').value),description:$('#productDescription').value,image_url:$('#productImage').value,active:$('#productActive').checked};try{await api(id?'/admin/products/'+id:'/admin/products',{method:id?'PATCH':'POST',body:JSON.stringify(b)});$('#productMessage').textContent='Saved.';clearProduct();await loadProducts();await loadSummary()}catch(e){$('#productMessage').textContent=e.message}};
function clearProduct(){$('#productForm').reset();$('#productId').value='';$('#productQty').value=0;$('#productReorder').value=5;$('#productActive').checked=true}$('#clearProduct').onclick=clearProduct;
async function toggleProduct(p){try{await api('/admin/products/'+p.id,{method:'PATCH',body:JSON.stringify({active:!p.active})});loadProducts()}catch(e){alert(e.message)}}
async function loadCustomers(){const r=await api('/admin/customers');customers=r.data||[];$('#customers').innerHTML=customers.map(c=>'<div class="card"><div class="card-head"><strong>'+esc(c.full_name||'Customer')+'</strong><span class="tag">CUSTOMER</span></div><div>'+esc(c.phone||'No phone')+'</div><small>Joined '+new Date(c.created_at).toLocaleDateString()+'</small></div>').join('')||'<div class="card">No customers.</div>'}
async function loadReviews(){const r=await api('/admin/reviews');reviews=r.data||[];$('#reviews').innerHTML=reviews.map(x=>'<div class="card"><div class="card-head"><strong>'+esc(x.products?.name||'Product')+'</strong><span class="tag">'+esc(x.status)+'</span></div><div class="stars">'+('★'.repeat(x.rating))+'</div><p>'+esc(x.body)+'</p><small>'+esc(x.profiles?.full_name||'Customer')+' · '+new Date(x.created_at).toLocaleString()+'</small><div class="actions"><button class="btn" data-review="'+x.id+'" data-review-status="approved">Approve</button><button class="btn" data-review="'+x.id+'" data-review-status="rejected">Reject</button></div></div>').join('')||'<div class="card">No reviews.</div>';$$('[data-review]').forEach(b=>b.onclick=async()=>{try{await api('/admin/reviews/'+b.dataset.review,{method:'PATCH',body:JSON.stringify({status:b.dataset.reviewStatus})});loadReviews();loadSummary()}catch(e){alert(e.message)}})}
$('#orderSearch').oninput=renderOrders;$('#orderStatus').onchange=renderOrders;$('#refreshOrders').onclick=loadOrders;start();