const C=window.BHATTI_CONFIG;
const sb=window.supabase.createClient(C.supabaseUrl,C.supabasePublishableKey);
const API=C.apiBase.replace(/\/$/,'');
let products=[],filter='All',search='',sort='featured',session=null,currentProduct=null,authMode='login',cart=JSON.parse(localStorage.getItem('bhatti-cart')||'[]');
const categories=[['Lighting','LED bulbs & lighting','💡'],['Wires & Cables','Wiring & cables','〰'],['Switches & Sockets','Switchgear & accessories','▣'],['Breakers','MCBs & protection','⏚'],['Fans','Fans & ventilation','✣'],['PVC','Pipes & conduits','◯']];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], money=n=>'PKR '+Number(n||0).toLocaleString();
async function token(){const {data}=await sb.auth.getSession();return data.session?.access_token||''}
async function api(path,options={}){const t=await token();const r=await fetch(API+path,{...options,headers:{'Content-Type':'application/json',...(options.headers||{}),...(t?{Authorization:'Bearer '+t}:{})}});const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(body.error||'Request failed');return body}
function openModal(id){$(id).classList.add('open')}function closeModal(id){$(id).classList.remove('open')}
function saveCart(){localStorage.setItem('bhatti-cart',JSON.stringify(cart));renderCart();$('#cartCount').textContent=cart.reduce((n,x)=>n+x.quantity,0)}
function addCart(p){const x=cart.find(i=>i.product_id===p.id);if(x)x.quantity++;else cart.push({product_id:p.id,name:p.name,price:Number(p.price),quantity:1,category:p.category});saveCart();openCart()}
function renderCart(){const el=$('#cartItems');if(!cart.length){el.innerHTML='<div class="muted">Your bag is empty.</div>';$('#cartFoot').innerHTML='';return}el.innerHTML=cart.map((x,i)=>'<div class="cart-item"><div><h3>'+esc(x.name)+'</h3><p>'+money(x.price)+' · '+esc(x.category)+'</p></div><div class="qty"><button data-q="'+i+'" data-d="-1">−</button><b>'+x.quantity+'</b><button data-q="'+i+'" data-d="1">+</button><button data-remove="'+i+'">×</button></div></div>').join('');const total=cart.reduce((n,x)=>n+x.price*x.quantity,0);$('#cartFoot').innerHTML='<div class="cart-total"><span>Total</span><strong>'+money(total)+'</strong></div><button class="btn primary full" id="checkoutButton">Checkout ↗</button>';$$('[data-q]').forEach(b=>b.onclick=()=>{const i=+b.dataset.q;cart[i].quantity+=+b.dataset.d;if(cart[i].quantity<1)cart.splice(i,1);saveCart()});$$('[data-remove]').forEach(b=>b.onclick=()=>{cart.splice(+b.dataset.remove,1);saveCart()});$('#checkoutButton').onclick=checkout}
function openCart(){renderCart();$('#overlay').classList.add('open');$('#cartDrawer').classList.add('open')}function closeCart(){$('#overlay').classList.remove('open');$('#cartDrawer').classList.remove('open')}
function renderCategories(){const g=$('#categoriesGrid');g.innerHTML=categories.map(c=>'<button class="category" data-cat="'+esc(c[0])+'"><span class="icon">'+c[2]+'</span><strong>'+esc(c[0])+'</strong><small>'+esc(c[1])+'</small></button>').join('');$$('[data-cat]').forEach(b=>b.onclick=()=>{filter=b.dataset.cat;renderFilters();render()})}
function renderFilters(){const all=['All',...categories.map(x=>x[0])];$('#filters').innerHTML=all.map(x=>'<button class="'+(x===filter?'active':'')+'" data-filter="'+esc(x)+'">'+esc(x)+'</button>').join('');$$('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;renderFilters();render()})}
function filtered(){let list=products.filter(p=>(filter==='All'||p.category===filter)&&(!search||p.name.toLowerCase().includes(search)||String(p.category).toLowerCase().includes(search)));if(sort==='low')list.sort((a,b)=>a.price-b.price);if(sort==='high')list.sort((a,b)=>b.price-a.price);return list}
function stock(p){const q=Number(p.stock_quantity||0);return q<=0?'<span class="stock out">OUT OF STOCK</span>':q<6?'<span class="stock low">'+q+' LEFT</span>':'<span class="stock ok">'+q+' IN STOCK</span>'}
function render(){const list=filtered();$('#resultCount').textContent=list.length+' products';$('#productGrid').innerHTML=list.map(p=>'<article class="product"><div class="product-art" data-product="'+p.id+'">'+(p.image_url?'<img src="'+esc(p.image_url)+'" alt="" style="max-width:70%;max-height:80%">':'⚡')+'</div><div class="product-body"><small>'+esc(p.category)+'</small><h3>'+esc(p.name)+'</h3><p>'+esc(p.description||'Quality electrical product.')+'</p><div class="product-row"><strong>'+money(p.price)+'</strong>'+stock(p)+'</div><br><button data-add-product="'+p.id+'" '+(Number(p.stock_quantity||0)<=0?'disabled':'')+'>Add to bag</button></div></article>').join('');$$('[data-product]').forEach(b=>b.onclick=()=>showProduct(b.dataset.product));$$('[data-add-product]').forEach(b=>b.onclick=()=>addCart(products.find(p=>p.id===b.dataset.addProduct)))}
async function loadProducts(){try{const r=await api('/products');products=r.data||[];render()}catch(e){$('#productGrid').innerHTML='<p class="error">Catalogue could not be loaded. Please refresh or contact the store.</p>'}}
async function showProduct(id){const p=products.find(x=>x.id===id);if(!p)return;currentProduct=p;openModal('productModal');$('#productDetail').innerHTML='<div class="product-detail-grid"><div class="detail-art">'+(p.image_url?'<img src="'+esc(p.image_url)+'" alt="" style="max-width:80%;max-height:80%">':'⚡')+'</div><div class="detail-copy"><p class="eyebrow">'+esc(p.category)+'</p><h2>'+esc(p.name)+'</h2><h3>'+money(p.price)+'</h3><p>'+esc(p.description||'')+'</p><p>'+stock(p)+'</p><button class="btn primary" '+(Number(p.stock_quantity||0)<=0?'disabled':'')+' id="detailAdd">Add to bag ↗</button><div id="productReviews" class="review-grid" style="margin-top:25px"></div></div></div>';$('#detailAdd').onclick=()=>addCart(p);loadReviews(p.id)}
async function loadReviews(id){try{const r=await api('/reviews/product/'+id);$('#productReviews').innerHTML=(r.data||[]).map(x=>'<div class="review-card"><div class="stars">'+('★'.repeat(x.rating))+'</div><p>'+esc(x.body)+'</p><small>'+esc(x.profiles?.full_name||'Verified customer')+'</small></div>').join('')||'<p class="muted">No approved reviews yet.</p>'}catch{}}
function setAuthMode(mode){authMode=mode;$('#authTitle').textContent=mode==='login'?'Sign in.':'Create your account.';$('#authIntro').textContent=mode==='login'?'Sign in to save addresses and track orders.':'Create an account to keep your orders and delivery details together.';$('#nameField').style.display=mode==='login'?'none':'grid';$('#authMode').textContent=mode==='login'?'Create a new account':'I already have an account';$('#authMessage').textContent=''}
async function handleAuth(e){e.preventDefault();const email=$('#authEmail').value.trim(),password=$('#authPassword').value,name=$('#authName').value.trim();try{let r;if(authMode==='login')r=await sb.auth.signInWithPassword({email,password});else r=await sb.auth.signUp({email,password,options:{data:{full_name:name},emailRedirectTo:location.href}});if(r.error)throw r.error;if(authMode==='signup'&&!r.data.session){$('#authMessage').textContent='Check your email to verify your account, then sign in.';return}closeModal('authModal')}catch(e){$('#authMessage').textContent=e.message}}
async function refreshSession(){const {data}=await sb.auth.getSession();session=data.session||null;if(session){try{const p=await api('/account/profile');$('#accountName').textContent=p.data.full_name||'Customer';$('#accountEmail').textContent=session.user.email;$('#profileName').value=p.data.full_name||'';$('#profilePhone').value=p.data.phone||'';$('#profileEmail').value=session.user.email}catch{}}}
async function openAccount(){if(!session){openModal('authModal');return}await refreshSession();openModal('accountModal');loadAddresses();loadOrders()}
async function loadAddresses(){const r=await api('/account/addresses');$('#addressList').innerHTML=(r.data||[]).map(a=>'<div class="address-card"><strong>'+esc(a.label)+(a.is_default?' · DEFAULT':'')+'</strong><span>'+esc(a.recipient_name||'')+' · '+esc(a.phone||'')+'</span><p>'+esc(a.address_line)+', '+esc(a.city)+'</p></div>').join('')||'<p class="muted">No saved addresses yet.</p>'}
async function loadOrders(){const r=await api('/orders/me');$('#myOrders').innerHTML=(r.data||[]).map(o=>'<div class="order-card"><strong>'+esc(o.order_number)+' · '+esc(o.status)+'</strong><span>'+new Date(o.created_at).toLocaleString()+' · '+money(o.total)+'</span><p>'+o.order_items.map(i=>esc(i.product_name)+' × '+i.quantity).join('<br>')+'</p><small>Payment: '+esc(o.payment_status)+' · '+esc(o.payment_method)+'</small></div>').join('')||'<p class="muted">No orders yet.</p>'}
async function saveProfile(e){e.preventDefault();try{await api('/account/profile',{method:'PATCH',body:JSON.stringify({full_name:$('#profileName').value,phone:$('#profilePhone').value})});await refreshSession()}catch(e){alert(e.message)}}
async function saveAddress(e){e.preventDefault();const b={label:$('#addressLabel').value,recipient_name:$('#addressRecipient').value,phone:$('#addressPhone').value,city:$('#addressCity').value,address_line:$('#addressText').value,is_default:$('#addressDefault').checked};try{await api($('#addressId').value?'/account/addresses/'+$('#addressId').value:'/account/addresses',{method:$('#addressId').value?'PUT':'POST',body:JSON.stringify(b)});e.target.reset();$('#addressId').value='';loadAddresses()}catch(e){alert(e.message)}}
async function checkout(){if(!session){closeCart();openModal('authModal');return}closeCart();$('#checkoutPhone').value='';try{const r=await api('/account/addresses');const a=r.data?.find(x=>x.is_default)||r.data?.[0];if(a){$('#checkoutAddress').value=a.address_line;$('#checkoutCity').value=a.city;$('#checkoutPhone').value=a.phone||''}}catch{}$('#checkoutTotal').textContent=money(cart.reduce((n,x)=>n+x.price*x.quantity,0));openModal('checkoutModal')}
async function placeOrder(e){e.preventDefault();try{const b={customer_name:$('#profileName').value||'Customer',customer_phone:$('#checkoutPhone').value,customer_email:session.user.email,city:$('#checkoutCity').value,address_line:$('#checkoutAddress').value,payment_method:$('#checkoutPayment').value,note:$('#checkoutNote').value,items:cart.map(x=>({product_id:x.product_id,quantity:x.quantity}))};const r=await api('/orders',{method:'POST',body:JSON.stringify(b)});cart=[];saveCart();closeModal('checkoutModal');alert('Order '+r.data.order_number+' placed successfully.');loadProducts()}catch(e){$('#checkoutMessage').textContent=e.message}}
async function subscribe(e){e.preventDefault();try{await api('/newsletter',{method:'POST',body:JSON.stringify({email:$('#newsletterEmail').value})});$('#newsletterMessage').textContent='You are on the store update list.';e.target.reset()}catch(e){$('#newsletterMessage').textContent=e.message}}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
$('#year').textContent=new Date().getFullYear();renderCategories();renderFilters();saveCart();loadProducts();refreshSession();
$('.menu').onclick=()=>document.querySelector('nav').classList.toggle('open');$('#searchButton').onclick=()=>$('#productSearch').focus();$('#accountButton').onclick=openAccount;$('#cartButton').onclick=openCart;$('#overlay').onclick=closeCart;$$('[data-close]').forEach(b=>b.onclick=()=>closeModal(b.dataset.close));$('#authMode').onclick=()=>setAuthMode(authMode==='login'?'signup':'login');$('#authForm').onsubmit=handleAuth;$('#profileForm').onsubmit=saveProfile;$('#addressForm').onsubmit=saveAddress;$('#checkoutForm').onsubmit=placeOrder;$('#newsletterForm').onsubmit=subscribe;$('#signOut').onclick=async()=>{await sb.auth.signOut();session=null;closeModal('accountModal')};$$('.tabs button').forEach(b=>b.onclick=()=>{$$('.tabs button').forEach(x=>x.classList.remove('active'));$$('.account-panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('[data-panel="'+b.dataset.tab+'"]').classList.add('active')});$('#productSearch').oninput=e=>{search=e.target.value.toLowerCase();render()};$('#sort').onchange=e=>{sort=e.target.value;render()};sb.auth.onAuthStateChange((_event,s)=>{session=s});
setAuthMode('login');