const C=window.BHATTI_CONFIG;
const sb=window.supabase.createClient(C.supabaseUrl,C.supabasePublishableKey);
const API=C.apiBase.replace(/\/$/,'');
let products=[],filter='All',search='',sort='featured',session=null,currentProduct=null,authMode='login',cart=JSON.parse(localStorage.getItem('bhatti-cart')||'[]');
const categories=[['Lighting','LED, downlights, flood & emergency lighting','⚡'],['Wires & Cables','House wiring, flexible & power cables','〰'],['Switches & Sockets','Switches, sockets, plates & controls','▣'],['Circuit Protection','MCBs, RCCBs, DBs & protection','⏚'],['Fans','Ceiling, exhaust & ventilation products','✣'],['Conduit & PVC','PVC conduit, fittings & cable containment','◯']];const subcategories={'Lighting':['LED Bulbs','Downlights & Panels','Flood & Emergency Lights','Lamps & Holders'],'Wires & Cables':['House Wiring','Flexible Cable','Power Cable','Data & Control'],'Switches & Sockets':['Switches','Sockets','Plates','Dimmers & Regulators'],'Circuit Protection':['MCBs','RCCBs / RCBOs','Distribution Boards','Protection Accessories'],'Fans':['Ceiling Fans','Exhaust Fans','Regulators','Ventilation Accessories'],'Conduit & PVC':['PVC Conduit','Fittings','Junction Boxes','Cable Management']};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], money=n=>'PKR '+Number(n||0).toLocaleString();
async function token(){const {data}=await sb.auth.getSession();return data.session?.access_token||''}
async function api(path,options={}){const t=await token();const r=await fetch(API+path,{...options,headers:{'Content-Type':'application/json',...(options.headers||{}),...(t?{Authorization:'Bearer '+t}:{})}});const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(body.error||'Request failed');return body}
function openModal(id){const el=$(id);if(el)el.classList.add('open')}function closeModal(id){const el=$(id);if(el)el.classList.remove('open')}
function saveCart(){localStorage.setItem('bhatti-cart',JSON.stringify(cart));renderCart();const count=$('#cartCount');if(count)count.textContent=cart.reduce((n,x)=>n+x.quantity,0)}
function addCart(p){const x=cart.find(i=>i.product_id===p.id);if(x)x.quantity++;else cart.push({product_id:p.id,name:p.name,price:Number(p.price),quantity:1,category:p.category});saveCart();openCart()}
function renderCart(){const el=$('#cartItems');if(!cart.length){el.innerHTML='<div class="muted">Your bag is empty.</div>';$('#cartFoot').innerHTML='';return}el.innerHTML=cart.map((x,i)=>'<div class="cart-item"><div><h3>'+esc(x.name)+'</h3><p>'+money(x.price)+' · '+esc(x.category)+'</p></div><div class="qty"><button data-q="'+i+'" data-d="-1">−</button><b>'+x.quantity+'</b><button data-q="'+i+'" data-d="1">+</button><button data-remove="'+i+'">×</button></div></div>').join('');const total=cart.reduce((n,x)=>n+x.price*x.quantity,0);$('#cartFoot').innerHTML='<div class="cart-total"><span>Total</span><strong>'+money(total)+'</strong></div><button class="btn primary full" id="checkoutButton">Checkout ↗</button>';$('[data-q]').forEach(b=>b.onclick=()=>{const i=+b.dataset.q;cart[i].quantity+=+b.dataset.d;if(cart[i].quantity<1)cart.splice(i,1);saveCart()});$('[data-remove]').forEach(b=>b.onclick=()=>{cart.splice(+b.dataset.remove,1);saveCart()});$('#checkoutButton').onclick=checkout}
function openCart(){renderCart();const overlay=$('#overlay'),drawer=$('#cartDrawer');if(overlay)overlay.classList.add('open');if(drawer)drawer.classList.add('open')}function closeCart(){const overlay=$('#overlay'),drawer=$('#cartDrawer');if(overlay)overlay.classList.remove('open');if(drawer)drawer.classList.remove('open')}
function renderCategories(){const g=$('#categoriesGrid');if(!g)return;g.innerHTML=categories.map((c,i)=>'<button type="button" class="category-card cat-'+['lighting','wires','switches','protection','fans','conduit'][i]+'" data-cat="'+esc(c[0])+'"><span>0'+(i+1)+' / '+esc(c[0])+'</span><strong>'+esc(c[0])+'</strong><small>'+esc(c[1])+'</small></button>').join('');$('#categoriesGrid [data-cat]').forEach(b=>b.onclick=()=>{filter=b.dataset.cat;renderFilters();render();document.querySelector('#products')?.scrollIntoView({behavior:'smooth'})})}
function renderFilters(){const main=filter.includes(' - ')?filter.split(' - ')[0]:filter;const all=['All',...categories.map(x=>x[0])];const current=subcategories[main]||[];$('#filters').innerHTML='<div class="main-filters">'+all.map(x=>'<button type="button" class="filter '+(x===main?'active':'')+'" data-filter="'+esc(x)+'">'+esc(x)+'</button>').join('')+'</div>'+(current.length?'<div class="sub-filters"><span class="sub-filter-label">Explore '+esc(main)+':</span>'+current.map(x=>'<button type="button" class="sub-chip '+(filter===main+' - '+x?'active':'')+'" data-filter="'+esc(main+' - '+x)+'">'+esc(x)+'</button>').join('')+'</div>':'');$('#filters [data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;renderFilters();render()})}
function filtered(){let list=products.filter(p=>{if(filter==='All')return true;if(filter.includes(' - ')){const [main,sub]=filter.split(' - ');return p.category===main&&(p.name+' '+(p.description||'')).toLowerCase().includes(sub.toLowerCase().replace(/&/g,''))}return p.category===filter}).filter(p=>!search||p.name.toLowerCase().includes(search)||String(p.category).toLowerCase().includes(search));if(sort==='low')list.sort((a,b)=>a.price-b.price);if(sort==='high')list.sort((a,b)=>b.price-a.price);return list}
function stock(p){const q=Number(p.stock_quantity||0);return q<=0?'<span class="stock out">OUT OF STOCK</span>':q<6?'<span class="stock low">'+q+' LEFT</span>':'<span class="stock ok">'+q+' IN STOCK</span>'}
function productVisual(p){const label=esc((p.name||'').split(' ').slice(0,3).join(' '));const icon={Lighting:'◉','Wires & Cables':'〰','Switches & Sockets':'▣','Circuit Protection':'◈',Fans:'✣','Conduit & PVC':'◯'}[p.category]||'⚡';const svg='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 900 1125"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#e8e0cf"/><stop offset=".52" stop-color="#b8a98c"/><stop offset="1" stop-color="#536057"/></linearGradient><filter id="s"><feDropShadow dx="0" dy="24" stdDeviation="28" flood-opacity=".18"/></filter></defs><rect width="900" height="1125" fill="url(#g)"/><rect x="42" y="42" width="816" height="1041" rx="48" fill="rgba(255,255,255,.16)" stroke="rgba(255,255,255,.55)"/><circle cx="450" cy="470" r="190" fill="rgba(251,249,244,.48)" stroke="rgba(255,255,255,.7)" filter="url(#s)"/><text x="450" y="515" text-anchor="middle" font-family="Georgia,serif" font-size="210" fill="#24463b">'+icon+'</text><text x="70" y="930" font-family="Arial,sans-serif" font-size="30" font-weight="700" letter-spacing="4" fill="#11110f">BHATTI ELECTRIC</text><text x="70" y="985" font-family="Arial,sans-serif" font-size="25" fill="#5e5a51">'+label.replace(/&/g,'&amp;')+'</text><text x="70" y="1030" font-family="Arial,sans-serif" font-size="18" letter-spacing="5" fill="#9d7b43">FIELD READY / 2026</text></svg>';return 'data:image/svg+xml;charset=UTF-8,'+encodeURIComponent(svg)}
function productCards(list){if(!list.length)return '<p class="catalog-empty">No electrical products in this edit yet.</p>';return list.map(p=>'<article class="product"><div class="pic"><button class="product-image-button" type="button" data-product="'+p.id+'"><img loading="lazy" src="'+(p.image_url?esc(p.image_url):productVisual(p))}" alt="'+esc(p.name)+'"></button><button class="heart" type="button" data-add-product="'+p.id+'">＋</button><button class="quick-view" type="button" data-product="'+p.id+'">Quick view</button></div><div class="product-info"><div class="category-row"><span class="category">'+esc(p.category)+'</span>'+stock(p)+'</div><button class="product-title-button" type="button" data-product="'+p.id+'"><h3>'+esc(p.name)+'</h3></button><div class="price">'+money(p.price)+'</div><button class="add" type="button" data-add-product="'+p.id+'"><span>＋</span> Add to bag</button></div></article>').join('')}
function wireProductCards(root){root?.querySelectorAll('[data-product]').forEach(b=>b.onclick=()=>showProduct(b.dataset.product));root?.querySelectorAll('[data-add-product]').forEach(b=>b.onclick=()=>{const p=products.find(x=>x.id===b.dataset.addProduct);if(p)addCart(p)})}
function render(){const list=filtered();const count=$('#resultCount'),grid=$('#productGrid');if(count)count.textContent=list.length+' '+(list.length===1?'product':'products');if(grid){grid.innerHTML=list.length?productCards(list):'<div class="empty-state"><strong>No products found.</strong><span>Try another category, clear your search, or check back for new stock.</span><button type="button" class="btn" id="clearCatalogueFilters">Clear filters</button></div>';$('#clearCatalogueFilters')?.addEventListener('click',()=>{filter='All';search='';if($('#productSearch'))$('#productSearch').value='';renderFilters();render()});wireProductCards(grid)}const best=$('#bestGrid');if(best){best.innerHTML=productCards(list.slice(0,4));wireProductCards(best)}const fresh=$('#newGrid');if(fresh){const freshList=[...products].sort((a,b)=>String(b.created_at||'').localeCompare(String(a.created_at||''))).slice(0,4);fresh.innerHTML=productCards(freshList);wireProductCards(fresh)}}const FALLBACK_PRODUCTS=[
{id:'demo-lgt-1',name:'24W Cool White LED Bulb',category:'Lighting',price:850,description:'Energy-efficient LED bulb for homes and shops.',sku:'BH-LGT-003',active:true,stock_quantity:20},
{id:'demo-lgt-2',name:'50W LED Flood Light',category:'Lighting',price:3250,description:'Bright outdoor flood light for practical project use.',sku:'BH-LGT-004',active:true,stock_quantity:12},
{id:'demo-wir-1',name:'2.5mm² Twin & Earth Cable 90m',category:'Wires & Cables',price:14200,description:'Reliable house wiring cable for installation work.',sku:'BH-WIR-003',active:true,stock_quantity:8},
{id:'demo-wir-2',name:'4mm² Single Core Copper Cable 90m',category:'Wires & Cables',price:21500,description:'Copper single-core cable for demanding electrical runs.',sku:'BH-WIR-004',active:true,stock_quantity:8},
{id:'demo-swt-1',name:'20A 2-Way Modular Switch',category:'Switches & Sockets',price:560,description:'Clean modular switch for residential and commercial use.',sku:'BH-SWT-003',active:true,stock_quantity:18},
{id:'demo-swt-2',name:'2-Gang Universal Socket with USB',category:'Switches & Sockets',price:1450,description:'Modern universal socket with convenient USB charging.',sku:'BH-SWT-004',active:true,stock_quantity:14},
{id:'demo-cpr-1',name:'32A Single Pole MCB',category:'Circuit Protection',price:680,description:'Compact circuit protection for distribution boards.',sku:'BH-CPR-003',active:true,stock_quantity:20},
{id:'demo-cpr-2',name:'63A Double Pole MCB',category:'Circuit Protection',price:1250,description:'Double-pole protection for residential and commercial circuits.',sku:'BH-CPR-004',active:true,stock_quantity:15},
{id:'demo-fan-1',name:'48 Inch Ceiling Fan',category:'Fans',price:10800,description:'Practical ceiling fan for everyday cooling.',sku:'BH-FAN-003',active:true,stock_quantity:9},
{id:'demo-fan-2',name:'16 Inch Wall Exhaust Fan',category:'Fans',price:5200,description:'Compact exhaust fan for ventilation and utility spaces.',sku:'BH-FAN-004',active:true,stock_quantity:11},
{id:'demo-pvc-1',name:'25mm PVC Conduit 3m',category:'Conduit & PVC',price:290,description:'Durable PVC conduit for protected cable routing.',sku:'BH-PVC-003',active:true,stock_quantity:30},
{id:'demo-pvc-2',name:'25mm PVC Conduit Tee',category:'Conduit & PVC',price:95,description:'PVC tee fitting for neat conduit installations.',sku:'BH-PVC-004',active:true,stock_quantity:40}
];
async function loadProducts(){const grid=$('#productGrid');if(grid)grid.innerHTML='<div class="catalogue-loading"><span></span><p>Loading live catalogue…</p></div>';try{const {data,error}=await sb.from('products').select('id,name,category,category_id,price,description,sku,image_url,active,created_at,updated_at').eq('active',true).order('name');if(error)throw error;const rows=data||[];const ids=rows.map(p=>p.id);let inventoryByProduct={};if(ids.length){const inv=await sb.from('inventory').select('product_id,quantity').in('product_id',ids);if(!inv.error)for(const row of inv.data||[])inventoryByProduct[row.product_id]=Number(row.quantity||0)}products=rows.map(p=>({...p,stock_quantity:inventoryByProduct[p.id]??0}));if(products.length){render();return}}catch(e){console.warn('Supabase catalogue read failed',e)}try{const r=await api('/products');if(Array.isArray(r.data)&&r.data.length){products=r.data;render();return}}catch(e){console.warn('Backend catalogue read failed',e)}products=FALLBACK_PRODUCTS;render()}async function showProduct(id){const p=products.find(x=>x.id===id);if(!p)return;currentProduct=p;openModal('productModal');$('#productDetail').innerHTML='<div class="product-detail-grid"><div class="detail-art">'+(p.image_url?'<img src="'+esc(p.image_url)+'" alt="" style="max-width:80%;max-height:80%">':'⚡')+'</div><div class="detail-copy"><p class="eyebrow">'+esc(p.category)+'</p><h2>'+esc(p.name)+'</h2><h3>'+money(p.price)+'</h3><p>'+esc(p.description||'')+'</p><p>'+stock(p)+'</p><button class="btn primary" '+(Number(p.stock_quantity||0)<=0?'disabled':'')+' id="detailAdd">Add to bag ↗</button><div id="productReviews" class="review-grid" style="margin-top:25px"></div><div id="reviewFormWrap" style="margin-top:25px"></div></div></div>';$('#detailAdd').onclick=()=>addCart(p);loadReviews(p.id);renderReviewForm(p)}
async function loadReviews(id){try{const r=await api('/reviews/product/'+id);$('#productReviews').innerHTML=(r.data||[]).map(x=>'<div class="review-card"><div class="stars">'+('★'.repeat(x.rating))+'</div><p>'+esc(x.body)+'</p><small>'+esc(x.profiles?.full_name||'Verified customer')+'</small></div>').join('')||'<p class="muted">No approved reviews yet.</p>'}catch{}}
async function renderReviewForm(p){if(!session){$('#reviewFormWrap').innerHTML='<p class="muted">Sign in after delivery to leave a verified review.</p>';return}try{const r=await api('/orders/me');const delivered=(r.data||[]).filter(o=>o.status==='Delivered'&&o.order_items.some(i=>i.product_id===p.id));if(!delivered.length){$('#reviewFormWrap').innerHTML='<p class="muted">Reviews unlock after this product is delivered.</p>';return}$('#reviewFormWrap').innerHTML='<form id="reviewForm"><p class="eyebrow">VERIFIED PURCHASE</p><label>Order<select id="reviewOrder">'+delivered.map(o=>'<option value="'+o.id+'">'+esc(o.order_number)+'</option>').join('')+'</select></label><label>Rating<select id="reviewRating"><option value="5">5 — Excellent</option><option value="4">4 — Very good</option><option value="3">3 — Good</option><option value="2">2 — Fair</option><option value="1">1 — Poor</option></select></label><label>Your review<textarea id="reviewBody" minlength="10" maxlength="800" required></textarea></label><button class="btn" type="submit">Send for approval ↗</button><p id="reviewMessage"></p></form>';$('#reviewForm').onsubmit=async e=>{e.preventDefault();try{await api('/reviews',{method:'POST',body:JSON.stringify({product_id:p.id,order_id:$('#reviewOrder').value,rating:Number($('#reviewRating').value),body:$('#reviewBody').value})});$('#reviewMessage').textContent='Review submitted for approval.';e.target.reset()}catch(e){$('#reviewMessage').textContent=e.message}}}catch(e){$('#reviewFormWrap').innerHTML='<p class="muted">Sign in to see eligible delivered orders.</p>'}}
function setAuthMode(mode){authMode=mode;const title=$('#authTitle'),intro=$('#authIntro'),name=$('#nameField'),toggle=$('#authMode'),forgot=$('#forgotPassword'),resend=$('#resendConfirmation'),msg=$('#authMessage');if(title)title.textContent=mode==='login'?'Sign in.':'Create your account.';if(intro)intro.textContent=mode==='login'?'Sign in to save addresses and track orders.':'Create an account to keep your orders and delivery details together.';if(name)name.style.display=mode==='login'?'none':'grid';if(toggle)toggle.textContent=mode==='login'?'Create a new account':'I already have an account';if(forgot)forgot.style.display=mode==='login'?'inline-block':'none';if(resend)resend.style.display=mode==='signup'?'inline-block':'none';if(msg)msg.textContent=''}
async function handleAuth(e){e.preventDefault();const email=$('#authEmail')?.value.trim()||'',password=$('#authPassword')?.value||'',name=$('#authName')?.value.trim()||'',submit=$('#authSubmit'),msg=$('#authMessage');if(submit)submit.disabled=true;try{let r;if(authMode==='login')r=await sb.auth.signInWithPassword({email,password});else r=await sb.auth.signUp({email,password,options:{data:{full_name:name},emailRedirectTo:location.origin+location.pathname}});if(r.error)throw r.error;if(authMode==='signup'&&!r.data.session){if(msg)msg.textContent='Account created. Check your email inbox (and spam/junk) and click the confirmation link before signing in.';const resend=$('#resendConfirmation');if(resend)resend.style.display='inline-block';return}closeModal('authModal')}catch(e){const m=String(e.message||e),low=m.toLowerCase();if(msg)msg.textContent=low.includes('email not confirmed')?'Your email is not confirmed yet. Check your inbox or use “Resend confirmation email”.':low.includes('rate limit')||low.includes('rate_limit')?'Supabase email sending is temporarily rate-limited. Wait before requesting another confirmation/reset email, then try again.':m}finally{if(submit)submit.disabled=false}}
async function refreshSession(){const {data}=await sb.auth.getSession();session=data.session||null;if(session){try{const p=await api('/account/profile');$('#accountName').textContent=p.data.full_name||'Customer';$('#accountEmail').textContent=session.user.email;$('#profileName').value=p.data.full_name||'';$('#profilePhone').value=p.data.phone||'';$('#profileEmail').value=session.user.email}catch{}}}
async function openAccount(){try{const {data}=await sb.auth.getSession();session=data.session||session||null}catch{} if(!session){setAuthMode('login');openModal('authModal');return} openModal('accountModal'); try{await refreshSession()}catch(e){console.warn('Account profile unavailable',e)} try{await loadAddresses()}catch(e){const el=$('#addressList');if(el)el.innerHTML='<p class="muted">Addresses are temporarily unavailable. You can still edit your profile.</p>'} try{await loadOrders()}catch(e){const el=$('#myOrders');if(el)el.innerHTML='<p class="muted">Orders are temporarily unavailable. Please try again shortly.</p>'}}
async function loadAddresses(){const r=await api('/account/addresses');$('#addressList').innerHTML=(r.data||[]).map(a=>'<div class="address-card"><strong>'+esc(a.label)+(a.is_default?' · DEFAULT':'')+'</strong><span>'+esc(a.recipient_name||'')+' · '+esc(a.phone||'')+'</span><p>'+esc(a.address_line)+', '+esc(a.city)+'</p></div>').join('')||'<p class="muted">No saved addresses yet.</p>'}
async function loadOrders(){const r=await api('/orders/me');$('#myOrders').innerHTML=(r.data||[]).map(o=>'<div class="order-card"><strong>'+esc(o.order_number)+' · '+esc(o.status)+'</strong><span>'+new Date(o.created_at).toLocaleString()+' · '+money(o.total)+'</span><p>'+o.order_items.map(i=>esc(i.product_name)+' × '+i.quantity).join('<br>')+'</p><small>Payment: '+esc(o.payment_status)+' · '+esc(o.payment_method)+'</small><div class="actions">'+(['Pending','Confirmed'].includes(o.status)?'<button class="btn" data-cancel-order="'+o.id+'">Request cancellation</button>':'')+(o.status==='Delivered'?'<button class="btn" data-return-order="'+o.id+'">Request return</button>':'')+'</div></div>').join('')||'<p class="muted">No orders yet.</p>'}
async function orderAction(id,action){const reason=prompt(action==='cancel'?'Cancellation reason (optional):':'Return reason (optional):')||'';try{await api('/orders/'+id+'/action',{method:'POST',body:JSON.stringify({action,reason})});loadOrders()}catch(e){alert(e.message)}}
async function saveProfile(e){e.preventDefault();try{await api('/account/profile',{method:'PATCH',body:JSON.stringify({full_name:$('#profileName').value,phone:$('#profilePhone').value})});await refreshSession()}catch(e){alert(e.message)}}
async function saveAddress(e){e.preventDefault();const b={label:$('#addressLabel').value,recipient_name:$('#addressRecipient').value,phone:$('#addressPhone').value,city:$('#addressCity').value,address_line:$('#addressText').value,is_default:$('#addressDefault').checked};try{await api($('#addressId').value?'/account/addresses/'+$('#addressId').value:'/account/addresses',{method:$('#addressId').value?'PUT':'POST',body:JSON.stringify(b)});e.target.reset();$('#addressId').value='';loadAddresses()}catch(e){alert(e.message)}}
async function checkout(){if(!session){closeCart();openModal('authModal');return}closeCart();$('#checkoutPhone').value='';try{const r=await api('/account/addresses');const a=r.data?.find(x=>x.is_default)||r.data?.[0];if(a){$('#checkoutAddress').value=a.address_line;$('#checkoutCity').value=a.city;$('#checkoutPhone').value=a.phone||''}}catch{}$('#checkoutTotal').textContent=money(cart.reduce((n,x)=>n+x.price*x.quantity,0));openModal('checkoutModal')}
async function placeOrder(e){e.preventDefault();try{const b={customer_name:$('#profileName').value||'Customer',customer_phone:$('#checkoutPhone').value,customer_email:session.user.email,city:$('#checkoutCity').value,address_line:$('#checkoutAddress').value,payment_method:$('#checkoutPayment').value,note:$('#checkoutNote').value,items:cart.map(x=>({product_id:x.product_id,quantity:x.quantity}))};const r=await api('/orders',{method:'POST',body:JSON.stringify(b)});cart=[];saveCart();closeModal('checkoutModal');alert('Order '+r.data.order_number+' placed successfully.');loadProducts()}catch(e){$('#checkoutMessage').textContent=e.message}}
async function subscribe(e){e.preventDefault();try{await api('/newsletter',{method:'POST',body:JSON.stringify({email:$('#newsletterEmail').value})});$('#newsletterMessage').textContent='You are on the store update list.';e.target.reset()}catch(e){$('#newsletterMessage').textContent=e.message}}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
$('#year').textContent=new Date().getFullYear();renderCategories();renderFilters();saveCart();loadProducts();refreshSession();
const menu=$('.menu');if(menu)menu.onclick=()=>{const nav=document.querySelector('nav');if(nav)nav.classList.toggle('open')};const searchButton=$('#searchButton');if(searchButton)searchButton.onclick=()=>$('#productSearch')?.focus();const accountButton=$('#accountButton');if(accountButton)accountButton.onclick=openAccount;const cartButton=$('#cartButton');if(cartButton)cartButton.onclick=openCart;const overlay=$('#overlay');if(overlay)overlay.onclick=closeCart;$('[data-close]').forEach(b=>b.onclick=()=>{const id=b.dataset.close;if(id==='cartDrawer')closeCart();else closeModal(id)});const authModeButton=$('#authMode');if(authModeButton)authModeButton.onclick=()=>setAuthMode(authMode==='login'?'signup':'login');const authForm=$('#authForm');if(authForm)authForm.onsubmit=handleAuth;const resendButton=$('#resendConfirmation');if(resendButton)resendButton.onclick=resendConfirmation;const forgotButton=$('#forgotPassword');if(forgotButton)forgotButton.onclick=forgotPassword;const profileForm=$('#profileForm');if(profileForm)profileForm.onsubmit=saveProfile;const addressForm=$('#addressForm');if(addressForm)addressForm.onsubmit=saveAddress;const checkoutForm=$('#checkoutForm');if(checkoutForm)checkoutForm.onsubmit=placeOrder;const newsletterForm=$('#newsletterForm');if(newsletterForm)newsletterForm.onsubmit=subscribe;const signOut=$('#signOut');if(signOut)signOut.onclick=async()=>{await sb.auth.signOut();session=null;closeModal('accountModal')};$('.tabs button').forEach(b=>b.onclick=()=>{$('.tabs button').forEach(x=>x.classList.remove('active'));$('.account-panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');const panel=$('[data-panel="'+b.dataset.tab+'"]');if(panel)panel.classList.add('active')});const productSearch=$('#productSearch');if(productSearch)productSearch.oninput=e=>{search=e.target.value.toLowerCase();render()};const sortSelect=$('#sort');if(sortSelect)sortSelect.onchange=e=>{sort=e.target.value;render()};sb.auth.onAuthStateChange((_event,s)=>{session=s; if(s){closeModal('authModal')}});
async function resendConfirmation(){const email=$('#authEmail').value.trim();if(!email){$('#authMessage').textContent='Enter your email address first.';return}try{const r=await sb.auth.resend({type:'signup',email,options:{emailRedirectTo:location.origin+location.pathname}});if(r.error)throw r.error;$('#authMessage').textContent='Confirmation email sent. Check your inbox and spam/junk folder.'}catch(e){$('#authMessage').textContent=e.message}}
async function forgotPassword(){const email=$('#authEmail').value.trim();if(!email){$('#authMessage').textContent='Enter your email address first.';return}try{const r=await sb.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});if(r.error)throw r.error;$('#authMessage').textContent='Password reset email sent. Check your inbox and spam/junk folder.'}catch(e){$('#authMessage').textContent=e.message}}
window.openCart=openCart;window.closeCart=closeCart;window.openAccount=openAccount;setAuthMode('login');