window.BHATTI=window.BHATTI||{};BHATTI.GUEST_CART_KEY='loca_guest_cart_v4';BHATTI.readGuestCart=()=>{try{return JSON.parse(localStorage.getItem(BHATTI.GUEST_CART_KEY)||'{}')}catch{return{}}};BHATTI.writeGuestCart=cart=>localStorage.setItem(BHATTI.GUEST_CART_KEY,JSON.stringify(cart||{}));BHATTI.cartTotalQuantity=()=>Object.values(BHATTI.cart||{}).reduce((s,q)=>s+Number(q||0),0);
BHATTI.loadServerCart=async uid=>{const{data,error}=await BHATTI.db.from('cart_items').select('product_id,quantity').eq('user_id',uid);if(error)throw error;return Object.fromEntries((data||[]).map(r=>[String(r.product_id),Number(r.quantity)]))};
BHATTI.mergeGuestCartIntoAccount=async uid=>{const guest=BHATTI.readGuestCart();if(!Object.keys(guest).length)return;const server=await BHATTI.loadServerCart(uid);const rows=Object.entries(guest).map(([product_id,quantity])=>({user_id:uid,product_id:Number(product_id),quantity:Math.min(20,Number(quantity)+Number(server[product_id]||0)),updated_at:new Date().toISOString()}));if(rows.length){const{error}=await BHATTI.db.from('cart_items').upsert(rows,{onConflict:'user_id,product_id'});if(error)throw error}BHATTI.writeGuestCart({})};
BHATTI.loadCart=async({mergeGuest=false}={})=>{try{if(BHATTI.currentUser){if(mergeGuest)await BHATTI.mergeGuestCartIntoAccount(BHATTI.currentUser.id);BHATTI.cart=await BHATTI.loadServerCart(BHATTI.currentUser.id)}else BHATTI.cart=BHATTI.readGuestCart();drawCart()}catch(err){console.warn('Cart sync failed',err);BHATTI.cart=BHATTI.readGuestCart();drawCart()}};
BHATTI.persistCartItem=async(id,q)=>{if(!BHATTI.currentUser){BHATTI.writeGuestCart(BHATTI.cart);return}if(q<=0){const{error}=await BHATTI.db.from('cart_items').delete().eq('user_id',BHATTI.currentUser.id).eq('product_id',Number(id));if(error)throw error}else{const{error}=await BHATTI.db.from('cart_items').upsert({user_id:BHATTI.currentUser.id,product_id:Number(id),quantity:Math.min(20,q),updated_at:new Date().toISOString()},{onConflict:'user_id,product_id'});if(error)throw error}};
async function addQuantity(id,quantity=1,{open=true}={}){const k=String(id),amount=Math.max(1,Math.min(20,Number(quantity)||1));BHATTI.cart[k]=Math.min(20,Number(BHATTI.cart[k]||0)+amount);drawCart();await BHATTI.persistCartItem(id,BHATTI.cart[k]);if(open)openCartDrawer()}async function add(id){return addQuantity(id,1)}async function removeItem(id){delete BHATTI.cart[String(id)];drawCart();await BHATTI.persistCartItem(id,0)}async function changeCartQty(id,d){const k=String(id),q=Math.max(0,Math.min(20,Number(BHATTI.cart[k]||0)+d));if(q)BHATTI.cart[k]=q;else delete BHATTI.cart[k];drawCart();await BHATTI.persistCartItem(id,q)}async function clearCart(){if(BHATTI.currentUser)await BHATTI.db.from('cart_items').delete().eq('user_id',BHATTI.currentUser.id);BHATTI.cart={};BHATTI.writeGuestCart({});drawCart()}
function drawCart(){const box=document.getElementById('cartItems'),foot=document.getElementById('cartFoot');if(!box||!foot)return;const entries=Object.entries(BHATTI.cart||{}).filter(([,q])=>Number(q)>0);if(!entries.length){box.innerHTML='<div class="empty">Your bag is waiting for something good.</div>';foot.innerHTML='';updateCartBadge();return}box.innerHTML=entries.map(([id,q])=>{const p=BHATTI.products.find(x=>String(x.id)===String(id));if(!p)return'';return`<div class="cart-item"><div class="mini"><img src="${BHATTI.escape(BHATTI.safeImage(p.image))}" alt=""></div><div class="cart-item-copy"><strong>${BHATTI.escape(p.name)}</strong><p>${BHATTI.money(p.price)}</p><div class="qty-row"><button type="button" onclick="changeCartQty(${id},-1)">−</button><span>${q}</span><button type="button" onclick="changeCartQty(${id},1)">＋</button><button type="button" class="remove-link" onclick="removeItem(${id})">Remove</button></div></div></div>`}).join('');const total=entries.reduce((s,[id,q])=>{const p=BHATTI.products.find(x=>String(x.id)===String(id));return s+(p?p.price*q:0)},0);foot.innerHTML=`<div class="cart-summary"><span>Subtotal</span><strong>${BHATTI.money(total)}</strong></div><button class="button primary" style="width:100%" onclick="openCheckout()">Checkout <span>↗</span></button>`;updateCartBadge()}
function updateCartBadge(){const b=document.getElementById('cartCount'),q=BHATTI.cartTotalQuantity();if(b){b.textContent=q>99?'99+':q;b.hidden=!q}}
function openCartDrawer(){document.getElementById('drawer')?.classList.add('open');document.getElementById('overlay')?.classList.add('open');document.body.classList.add('lock')}function toggleCart(){const d=document.getElementById('drawer'),o=document.getElementById('overlay');d?.classList.toggle('open');o?.classList.toggle('open');document.body.classList.toggle('lock',d?.classList.contains('open'))}
const originalAddQuantity=addQuantity;
addQuantity=async function(id,quantity=1,options={}){if(BHATTI.profile?.role==='admin'){BHATTI.notice?.({eyebrow:'Catalogue Preview Mode',title:'Admins cannot place orders.',message:'The storefront is read-only for Admin Studio catalogue review.',action:'Continue browsing'});return false}return originalAddQuantity(id,quantity,options)};
const originalChangeCartQty=changeCartQty;
changeCartQty=async function(id,delta){if(BHATTI.profile?.role==='admin'){BHATTI.notice?.({eyebrow:'Catalogue Preview Mode',title:'Admins cannot modify the bag.',message:'The storefront is read-only for Admin Studio catalogue review.',action:'Continue browsing'});return false}return originalChangeCartQty(id,delta)};
window.add=add;window.addQuantity=addQuantity;window.removeItem=removeItem;window.changeCartQty=changeCartQty;window.clearCart=clearCart;window.drawCart=drawCart;window.toggleCart=toggleCart;window.openCartDrawer=openCartDrawer;
