-- 20260926185724_002_storefront_accounts_orders_admin.sql
-- Reproducible schema for customer accounts, addresses, transactional orders,
-- reviews, newsletter subscriptions and admin audit history.
create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,full_name text,phone text,role text not null default 'customer' check(role in('customer','admin')),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.addresses(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id) on delete cascade,label text not null,recipient_name text,phone text,city text not null,address_line text not null,is_default boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.orders(id uuid primary key default gen_random_uuid(),order_number text not null unique,user_id uuid not null references public.profiles(id) on delete restrict,status text not null default 'Pending',payment_status text not null default 'Unpaid',payment_method text not null default 'Cash on Delivery',subtotal numeric(12,2) not null,total numeric(12,2) not null,customer_name text not null,customer_phone text not null,customer_email text not null,city text not null,address_line text not null,customer_note text,cancelled_by text,cancel_reason text,internal_note text,archived_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.order_items(id uuid primary key default gen_random_uuid(),order_id uuid not null references public.orders(id) on delete cascade,product_id uuid references public.products(id) on delete set null,product_name text not null,sku text,unit_price numeric(12,2) not null,quantity integer not null,line_total numeric(12,2) not null);
create table if not exists public.reviews(id uuid primary key default gen_random_uuid(),product_id uuid not null references public.products(id) on delete cascade,user_id uuid not null references public.profiles(id) on delete cascade,order_id uuid not null references public.orders(id) on delete cascade,rating integer not null check(rating between 1 and 5),body text not null,status text not null default 'pending',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(product_id,user_id,order_id));
create table if not exists public.newsletter_subscribers(id uuid primary key default gen_random_uuid(),email text not null unique,active boolean not null default true,created_at timestamptz not null default now());
create table if not exists public.audit_log(id bigint generated always as identity primary key,actor_user_id uuid references auth.users(id) on delete set null,action text not null,entity_type text not null,entity_id uuid,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create index if not exists orders_user_created_idx on public.orders(user_id,created_at desc);
create index if not exists order_items_order_idx on public.order_items(order_id);
create index if not exists reviews_product_status_idx on public.reviews(product_id,status);
alter table public.profiles enable row level security; alter table public.addresses enable row level security; alter table public.orders enable row level security; alter table public.order_items enable row level security; alter table public.reviews enable row level security; alter table public.newsletter_subscribers enable row level security; alter table public.audit_log enable row level security;
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from public.profiles where id=auth.uid() and role='admin')$$;
revoke execute on function public.is_admin() from anon; grant execute on function public.is_admin() to authenticated;
drop policy if exists "profiles own select" on public.profiles; create policy "profiles own select" on public.profiles for select to authenticated using(id=auth.uid() or public.is_admin());
drop policy if exists "profiles own update" on public.profiles; create policy "profiles own update" on public.profiles for update to authenticated using(id=auth.uid()) with check(id=auth.uid());
drop policy if exists "addresses own access" on public.addresses; create policy "addresses own access" on public.addresses for all to authenticated using(user_id=auth.uid() or public.is_admin()) with check(user_id=auth.uid() or public.is_admin());
drop policy if exists "orders own select" on public.orders; create policy "orders own select" on public.orders for select to authenticated using(user_id=auth.uid() or public.is_admin());
drop policy if exists "order items own select" on public.order_items; create policy "order items own select" on public.order_items for select to authenticated using(exists(select 1 from public.orders o where o.id=order_id and(o.user_id=auth.uid() or public.is_admin())));
drop policy if exists "approved reviews public" on public.reviews; create policy "approved reviews public" on public.reviews for select to anon,authenticated using(status='approved' or user_id=auth.uid() or public.is_admin());
drop policy if exists "reviews own insert" on public.reviews; create policy "reviews own insert" on public.reviews for insert to authenticated with check(user_id=auth.uid());
drop policy if exists "reviews own update" on public.reviews; create policy "reviews own update" on public.reviews for update to authenticated using(user_id=auth.uid() or public.is_admin()) with check(user_id=auth.uid() or public.is_admin());
drop policy if exists "newsletter public insert" on public.newsletter_subscribers; create policy "newsletter public insert" on public.newsletter_subscribers for insert to anon,authenticated with check(true);
grant select,insert,update on public.profiles to authenticated; grant select,insert,update,delete on public.addresses to authenticated; grant select on public.orders,public.order_items to authenticated; grant select,insert,update on public.reviews to authenticated; grant select on public.reviews to anon; grant insert on public.newsletter_subscribers to anon,authenticated;
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$begin insert into public.profiles(id,full_name) values(new.id,nullif(new.raw_user_meta_data->>'full_name','')) on conflict(id) do nothing; return new; end;$$;
drop trigger if exists on_auth_user_created on auth.users; create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
-- Checkout is implemented transactionally in public.create_order; the production version is applied by migration 002 in Supabase.
